version: '3'
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    depends_on:
      - ollama
